'use strict';

const ALL_HEALTHCARE_PROFESSIONS = ['doctor', 'nurse', 'practical_nurse'];

const WRITING_TASKS = [
  {
    taskId: 'writing.everyday.library-reply.a1',
    contentVersion: '2026-08-16.1',
    pathway: 'everyday',
    level: 'A1',
    title: 'Vastaa ystävälle',
    genre: 'short_message',
    register: 'informal',
    audience: 'Ystävä',
    situation: 'Ystäväsi lähettää viestin: “Tuletko huomenna kirjastoon kello 17?”',
    communicativeGoal: 'Kerro selkeästi, pääsetkö tulemaan, ja vahvista aika tai ehdota toinen aika.',
    prompt: 'Kirjoita ystävälle 2–3 lyhyttä lausetta suomeksi.',
    estimatedMinutes: 6,
    wordTarget: { min: 8, max: 35 },
    requiredEntitlements: ['learnAccess'],
    topic: 'meeting_plans',
    scaffolding: {
      showPhraseBank: true,
      planPrompts: [
        { id: 'answer', prompt: 'Pääsetkö tulemaan?', placeholder: 'Kyllä / en' },
        { id: 'time', prompt: 'Mikä aika sopii?', placeholder: 'Kello 17 / toinen aika' },
      ],
      phraseStarters: ['Hei!', 'Kyllä, tulen mielelläni.', 'Valitettavasti en pääse.', 'Sopisiko kello …?', 'Nähdään huomenna!'],
    },
    feedbackChecks: [
      {
        id: 'answer_invitation',
        area: 'communicative_goal',
        priority: 1,
        condition: { kind: 'includes_any', alternatives: ['tulen', 'sopii', 'pääsen', 'en pääse', 'en voi'] },
        successMessage: 'Vastasit kutsuun selkeästi.',
        title: 'Vastaa kutsuun suoraan',
        explanation: 'Ystävän pitää heti ymmärtää, pääsetkö mukaan.',
        retryInstruction: 'Lisää yksi suora vastaus: “Tulen”, “Pääsen” tai “En pääse”.',
      },
      {
        id: 'confirm_time',
        area: 'content',
        priority: 2,
        condition: { kind: 'includes_any', alternatives: ['17', 'viideltä', 'kello', 'aamulla', 'iltapäivällä', 'illalla'] },
        successMessage: 'Aika on helppo ymmärtää.',
        title: 'Vahvista aika',
        explanation: 'Aika tekee tapaamissuunnitelmasta käytännöllisen.',
        retryInstruction: 'Kirjoita sopiva aika tai ehdota uusi aika.',
      },
      {
        id: 'two_short_sentences',
        area: 'organization',
        priority: 3,
        condition: { kind: 'minimum_sentences', minimum: 2 },
        successMessage: 'Jaoit viestin lyhyisiin lauseisiin.',
        title: 'Kirjoita kaksi lyhyttä lausetta',
        explanation: 'Kaksi lyhyttä lausetta on tässä tilanteessa helpompi lukea kuin yksi pitkä lause.',
        retryInstruction: 'Erota vastaus ja aika omiksi lauseikseen.',
      },
    ],
    successCopy: 'Ystäväsi ymmärtää vastauksesi ja tapaamisen ajan.',
    developingCopy: 'Viestin aihe näkyy, mutta ystäväsi tarvitsee vielä suoran vastauksen.',
    originalContent: true,
  },
  {
    taskId: 'writing.everyday.appointment-change.a2',
    contentVersion: '2026-08-16.1',
    pathway: 'everyday',
    level: 'A2',
    title: 'Pyydä uusi aika',
    genre: 'service_message',
    register: 'neutral',
    audience: 'Hammashoitolan ajanvaraus',
    situation: 'Sinulla on hammashoitoaika tiistaina kello 10. Et pääse silloin. Torstai-iltapäivä sopii sinulle.',
    communicativeGoal: 'Peru alkuperäinen aika kohteliaasti ja pyydä uusi aika torstai-iltapäivälle.',
    prompt: 'Kirjoita lyhyt viesti ajanvaraukseen suomeksi.',
    estimatedMinutes: 8,
    wordTarget: { min: 20, max: 60 },
    requiredEntitlements: ['learnAccess'],
    topic: 'appointments',
    scaffolding: {
      showPhraseBank: true,
      planPrompts: [
        { id: 'old_time', prompt: 'Mikä aika ei sovi?', placeholder: 'Tiistai kello 10' },
        { id: 'request', prompt: 'Mitä pyydät?', placeholder: 'Uusi aika' },
        { id: 'new_time', prompt: 'Milloin pääset?', placeholder: 'Torstai-iltapäivä' },
      ],
      phraseStarters: ['Hei, minulla on aika …', 'En valitettavasti pääse silloin.', 'Voisinko saada uuden ajan …?', 'Ystävällisin terveisin'],
    },
    feedbackChecks: [
      {
        id: 'change_request',
        area: 'communicative_goal',
        priority: 1,
        condition: {
          kind: 'includes_each_group',
          groups: [
            ['uusi aika', 'uuden ajan', 'vaihtaa ajan', 'siirtää ajan'],
            ['torstai', 'torstaina'],
          ],
        },
        successMessage: 'Uuden ajan pyyntö on selkeä.',
        title: 'Yhdistä pyyntö ja uusi ajankohta',
        explanation: 'Ajanvaraus tarvitsee sekä pyynnön että tiedon siitä, milloin pääset.',
        retryInstruction: 'Pyydä uusi aika ja mainitse torstai-iltapäivä samassa viestissä.',
      },
      {
        id: 'old_time',
        area: 'content',
        priority: 2,
        condition: { kind: 'includes_each_group', groups: [['tiistai', 'tiistaina'], ['10', 'kymmeneltä']] },
        successMessage: 'Alkuperäinen aika löytyy viestistä.',
        title: 'Mainitse alkuperäinen aika',
        explanation: 'Ajanvaraus löytää varauksesi helpommin, kun kerrot nykyisen ajan.',
        retryInstruction: 'Lisää “tiistaina kello 10”.',
      },
      {
        id: 'polite_request',
        area: 'register',
        priority: 3,
        condition: { kind: 'includes_any', alternatives: ['voisinko', 'saisinko', 'kiitos', 'ystävällisin terveisin', 'valitettavasti'] },
        successMessage: 'Sävy sopii palveluviestiin.',
        title: 'Tee pyynnöstä kohtelias',
        explanation: 'Kohtelias pyyntö toimii paremmin ajanvarauksen viestissä.',
        retryInstruction: 'Käytä esimerkiksi muotoa “Voisinko saada uuden ajan?”',
      },
      {
        id: 'message_length',
        area: 'organization',
        priority: 4,
        condition: { kind: 'minimum_words', minimum: 20 },
        successMessage: 'Viestissä on tarpeeksi tietoa asian hoitamiseen.',
        title: 'Lisää yksi olennainen tieto',
        explanation: 'Liian lyhyt viesti voi jättää ajan tai pyynnön epäselväksi.',
        retryInstruction: 'Tarkista, että mukana ovat nykyinen aika, muutospyyntö ja uusi ajankohta.',
      },
    ],
    successCopy: 'Ajanvaraus ymmärtää, minkä ajan haluat vaihtaa ja milloin pääset.',
    developingCopy: 'Ajan vaihtaminen näkyy, mutta pyyntö tai uusi ajankohta tarvitsee vielä täsmennystä.',
    originalContent: true,
  },
  {
    taskId: 'writing.everyday.repair-email.b1',
    contentVersion: '2026-08-16.1',
    pathway: 'everyday',
    level: 'B1',
    title: 'Ilmoita huoltotarpeesta',
    genre: 'practical_email',
    register: 'neutral',
    audience: 'Vuokranantaja tai huoltoyhtiö',
    situation: 'Keittiön hana on vuotanut eilisestä lähtien. Vettä kertyy hitaasti altaan alle. Olet kotona arkipäivisin kello 16 jälkeen.',
    communicativeGoal: 'Kuvaa ongelma, kerro sen vaikutus ja pyydä korjauskäyntiä sopivana aikana.',
    prompt: 'Kirjoita selkeä huoltopyyntö suomeksi.',
    estimatedMinutes: 12,
    wordTarget: { min: 45, max: 110 },
    requiredEntitlements: ['learnAccess'],
    topic: 'housing',
    scaffolding: {
      showPhraseBank: false,
      planPrompts: [
        { id: 'problem', prompt: 'Mitä on tapahtunut ja milloin?', placeholder: 'Ongelma + alkamisaika' },
        { id: 'effect', prompt: 'Mitä ongelmasta seuraa?', placeholder: 'Konkreettinen vaikutus' },
        { id: 'action', prompt: 'Mitä pyydät ja milloin olet paikalla?', placeholder: 'Korjauspyyntö + sopiva aika' },
      ],
      phraseStarters: [],
    },
    feedbackChecks: [
      {
        id: 'repair_request',
        area: 'communicative_goal',
        priority: 1,
        condition: { kind: 'includes_any', alternatives: ['voisitteko korjata', 'huoltokäynti', 'korjauskäynti', 'pyydän korjaamaan', 'tulla korjaamaan'] },
        successMessage: 'Huoltoyhtiö ymmärtää, mitä pyydät.',
        title: 'Kirjoita selkeä toimintapyyntö',
        explanation: 'Ongelman kuvaus ei yksin kerro vastaanottajalle, mitä seuraavaksi pitäisi tehdä.',
        retryInstruction: 'Lisää suora mutta kohtelias pyyntö korjauskäynnistä.',
      },
      {
        id: 'problem_and_effect',
        area: 'content',
        priority: 2,
        condition: { kind: 'includes_each_group', groups: [['hana', 'vesihana'], ['vuotaa', 'vuotanut', 'vettä'], ['altaan alle', 'kaappiin', 'lattialle']] },
        successMessage: 'Ongelma ja sen vaikutus on kuvattu konkreettisesti.',
        title: 'Kuvaa vaikutus konkreettisesti',
        explanation: 'Konkreettinen vaikutus auttaa huoltoa arvioimaan kiireellisyyden.',
        retryInstruction: 'Kerro, mihin vettä kertyy tai mitä vahinkoa vuoto voi aiheuttaa.',
      },
      {
        id: 'availability',
        area: 'content',
        priority: 3,
        condition: { kind: 'includes_any', alternatives: ['kello 16', '16 jälkeen', 'neljän jälkeen', 'arkipäivisin', 'olen kotona'] },
        successMessage: 'Annoit korjauskäynnille sopivan ajan.',
        title: 'Kerro, milloin olet paikalla',
        explanation: 'Saatavuus helpottaa korjauskäynnin sopimista ilman lisäviestejä.',
        retryInstruction: 'Lisää, että olet kotona arkipäivisin kello 16 jälkeen.',
      },
      {
        id: 'connected_text',
        area: 'organization',
        priority: 4,
        condition: { kind: 'minimum_sentences', minimum: 4 },
        successMessage: 'Jäsensit huoltopynnön luettavaksi kokonaisuudeksi.',
        title: 'Jäsennä viesti neljään osaan',
        explanation: 'Ongelma, vaikutus, pyyntö ja sopiva aika erottuvat paremmin omissa lauseissaan.',
        retryInstruction: 'Tee jokaisesta pääasiasta oma lause.',
      },
    ],
    successCopy: 'Vastaanottaja ymmärtää huoltotarpeen ja tietää, mitä tehdä seuraavaksi.',
    developingCopy: 'Ongelma on tunnistettavissa, mutta selkeä korjauspyyntö puuttuu vielä.',
    originalContent: true,
  },
  {
    taskId: 'writing.professional.shift-update.b1',
    contentVersion: '2026-08-16.1',
    pathway: 'professional',
    level: 'B1',
    title: 'Kirjoita työvuoron tilannepäivitys',
    genre: 'internal_update',
    register: 'professional_neutral',
    audience: 'Esihenkilö ja seuraava työvuoro',
    situation: 'Fiktiivinen harjoitus: tärkeä toimitus myöhästyy 30 minuuttia. Asiakkaalle on ilmoitettu. Seuraavan vuoron pitää vahvistaa uusi aikataulu.',
    communicativeGoal: 'Anna tiivis tilannekuva: mitä tapahtui, mitä teit ja mitä seuraavan vuoron pitää tehdä.',
    prompt: 'Kirjoita sisäinen tilannepäivitys suomeksi. Käytä vain fiktiivisiä tietoja.',
    estimatedMinutes: 12,
    wordTarget: { min: 45, max: 100 },
    requiredEntitlements: ['professionalAccess'],
    allowedProfessions: ALL_HEALTHCARE_PROFESSIONS,
    topic: 'workplace_handover',
    scaffolding: {
      showPhraseBank: false,
      planPrompts: [
        { id: 'situation', prompt: 'Mikä muuttui?', placeholder: 'Muutos ja sen laajuus' },
        { id: 'action', prompt: 'Mitä on jo tehty?', placeholder: 'Tehty toimenpide' },
        { id: 'handover', prompt: 'Mitä seuraavan vuoron pitää tehdä?', placeholder: 'Selkeä jatkotehtävä' },
      ],
      phraseStarters: [],
    },
    feedbackChecks: [
      {
        id: 'handover_action',
        area: 'communicative_goal',
        priority: 1,
        condition: { kind: 'includes_each_group', groups: [['seuraava vuoro', 'seuraavassa vuorossa', 'iltavuoro', 'aamuvuoro'], ['vahvistaa', 'varmistaa', 'tarkistaa']] },
        successMessage: 'Seuraavan vuoron tehtävä on selkeä.',
        title: 'Nimeä seuraava vastuullinen toimija ja tehtävä',
        explanation: 'Tilannepäivitys onnistuu vasta, kun vastaanottaja tietää oman seuraavan toimintansa.',
        retryInstruction: 'Kirjoita, minkä vuoron pitää vahvistaa uusi aikataulu.',
      },
      {
        id: 'delay_fact',
        area: 'content',
        priority: 2,
        condition: { kind: 'includes_each_group', groups: [['toimitus'], ['30 minuuttia', 'puoli tuntia'], ['myöhästyy', 'viivästyy']] },
        successMessage: 'Viiveen olennainen tieto on täsmällinen.',
        title: 'Kerro viive täsmällisesti',
        explanation: 'Määrä ja kohde auttavat seuraavaa vuoroa tekemään oikean päätöksen.',
        retryInstruction: 'Mainitse, että toimitus viivästyy 30 minuuttia.',
      },
      {
        id: 'customer_informed',
        area: 'content',
        priority: 3,
        condition: { kind: 'includes_each_group', groups: [['asiakkaalle', 'asiakas'], ['ilmoitettu', 'kerrottu', 'tiedotettu']] },
        successMessage: 'Kerrottujen toimenpiteiden tila näkyy.',
        title: 'Kirjaa jo tehty toimenpide',
        explanation: 'Seuraavan vuoron ei pidä joutua arvaamaan, onko asiakkaalle jo ilmoitettu.',
        retryInstruction: 'Lisää tieto siitä, että asiakkaalle on ilmoitettu viiveestä.',
      },
      {
        id: 'neutral_register',
        area: 'register',
        priority: 4,
        condition: { kind: 'excludes_all', terms: ['ihan kamala', 'tosi paha', 'mokasivat', 'tyhmä'] },
        successMessage: 'Sävy on neutraali ja työpaikalle sopiva.',
        title: 'Pidä sävy havaintoihin perustuvana',
        explanation: 'Neutraali tilannepäivitys välittää faktat syyllistämättä ketään.',
        retryInstruction: 'Korvaa arvottava ilmaus konkreettisella havainnolla tai kellonajalla.',
      },
    ],
    successCopy: 'Seuraava vuoro saa käyttökelpoisen tilannekuvan ja selkeän jatkotehtävän.',
    developingCopy: 'Tilanteen aihe näkyy, mutta seuraavan vuoron tehtävä ei ole vielä riittävän selkeä.',
    privacyNotice: 'Käytä vain fiktiivisiä tietoja. Älä kirjoita oikeita potilas-, asiakas-, henkilöstö- tai muita henkilötietoja.',
    originalContent: true,
  },
  {
    taskId: 'writing.professional.incident-summary.b2',
    contentVersion: '2026-08-16.1',
    pathway: 'professional',
    level: 'B2',
    title: 'Laadi poikkeamatilanteen yhteenveto',
    genre: 'incident_summary',
    register: 'formal',
    audience: 'Esihenkilö ja sisäinen seurantaryhmä',
    situation: 'Fiktiivinen harjoitus: järjestelmä ei toiminut kello 9.20–10.05. Työ keskeytettiin, tukipalveluun otettiin yhteys ja järjestelmä palautui. Tiimin pitää sopia varamenettelystä.',
    communicativeGoal: 'Kuvaa tapahtumien aikajärjestys, vaikutus, tehdyt toimet, lopputulos ja yksi perusteltu jatkotoimi.',
    prompt: 'Kirjoita tiivis, neutraali poikkeamayhteenveto suomeksi. Käytä vain fiktiivisiä tietoja.',
    estimatedMinutes: 16,
    wordTarget: { min: 80, max: 170 },
    requiredEntitlements: ['professionalAccess'],
    allowedProfessions: ALL_HEALTHCARE_PROFESSIONS,
    topic: 'workplace_incident',
    scaffolding: {
      showPhraseBank: false,
      planPrompts: [
        { id: 'sequence', prompt: 'Mikä oli tapahtumien aikajärjestys?', placeholder: 'Alku, toimet, palautuminen' },
        { id: 'impact', prompt: 'Miten tilanne vaikutti työhön?', placeholder: 'Konkreettinen vaikutus' },
        { id: 'next_step', prompt: 'Mitä ehdotat jatkotoimeksi ja miksi?', placeholder: 'Toimi + perustelu' },
      ],
      phraseStarters: [],
    },
    feedbackChecks: [
      {
        id: 'complete_incident_arc',
        area: 'communicative_goal',
        priority: 1,
        condition: {
          kind: 'includes_each_group',
          groups: [
            ['9.20', '9:20'],
            ['10.05', '10:05'],
            ['keskeytettiin', 'keskeytyi'],
            ['palautui', 'saatiin toimimaan'],
          ],
        },
        successMessage: 'Tapahtumien alku, vaikutus ja lopputulos muodostavat ymmärrettävän kokonaisuuden.',
        title: 'Tee tapahtumaketjusta kokonainen',
        explanation: 'Poikkeamayhteenvedon lukijan pitää nähdä, milloin tilanne alkoi, mitä vaikutusta sillä oli ja milloin toiminta palautui.',
        retryInstruction: 'Tarkista, että mukana ovat molemmat kellonajat, työn keskeytys ja järjestelmän palautuminen.',
      },
      {
        id: 'actions_taken',
        area: 'content',
        priority: 2,
        condition: { kind: 'includes_each_group', groups: [['tukipalvelu', 'helpdesk', 'tukeen'], ['otettiin yhteyttä', 'ilmoitettiin', 'yhteys']] },
        successMessage: 'Tehdyt toimenpiteet on erotettu itse tapahtumasta.',
        title: 'Kirjaa tehty toimenpide',
        explanation: 'Yhteenveto tarvitsee tiedon siitä, miten tilanteeseen reagoitiin.',
        retryInstruction: 'Kerro, että tukipalveluun otettiin yhteyttä.',
      },
      {
        id: 'reasoned_follow_up',
        area: 'organization',
        priority: 3,
        condition: { kind: 'includes_each_group', groups: [['varamenettely', 'varajärjestely', 'toimintaohje'], ['jotta', 'koska', 'sen vuoksi']] },
        successMessage: 'Jatkotoimi on perusteltu eikä jää irralliseksi ehdotukseksi.',
        title: 'Perustele jatkotoimi',
        explanation: 'B2-tasoisessa ammatillisessa tekstissä ehdotuksen yhteys havaittuun ongelmaan pitää tehdä näkyväksi.',
        retryInstruction: 'Ehdota varamenettelyä ja perustele se esimerkiksi “jotta”-lauseella.',
      },
      {
        id: 'sufficient_detail',
        area: 'organization',
        priority: 4,
        condition: { kind: 'minimum_words', minimum: 80 },
        successMessage: 'Yhteenvedossa on riittävästi yksityiskohtia päätöksenteon tueksi.',
        title: 'Kehitä perustelua yhdellä yksityiskohdalla',
        explanation: 'Hyvin lyhyt teksti voi nimetä tapahtuman mutta jättää vaikutuksen tai jatkotoimen perustelun puuttumaan.',
        retryInstruction: 'Lisää yksi lause vaikutuksesta ja yksi lause jatkotoimen perustelusta.',
      },
      {
        id: 'formal_register',
        area: 'register',
        priority: 5,
        condition: { kind: 'excludes_all', terms: ['ihan sekaisin', 'tosi huono', 'mokasivat', 'joku tyyppi'] },
        successMessage: 'Rekisteri on neutraali ja muodolliseen työtekstiin sopiva.',
        title: 'Korvaa puhekielinen arvio havainnolla',
        explanation: 'Muodollinen yhteenveto perustuu havaintoihin, aikoihin ja tehtyihin toimiin.',
        retryInstruction: 'Poista arvottava ilmaus ja kirjoita sen tilalle tarkka tapahtuma tai vaikutus.',
      },
    ],
    successCopy: 'Lukija pystyy seuraamaan tapahtumaketjua ja arvioimaan ehdotettua jatkotoimea.',
    developingCopy: 'Poikkeama on tunnistettavissa, mutta tapahtumaketju tai lopputulos tarvitsee vielä täsmennystä.',
    privacyNotice: 'Käytä vain fiktiivisiä tietoja. Älä kirjoita oikeita potilas-, asiakas-, henkilöstö- tai muita henkilötietoja.',
    originalContent: true,
  },
];

function tasksForPathway(pathway, profession) {
  return WRITING_TASKS.filter((task) => {
    if (task.pathway !== pathway) return false;
    if (!profession || !task.allowedProfessions) return true;
    return task.allowedProfessions.includes(profession);
  });
}

function writingTaskById(taskId) {
  return WRITING_TASKS.find((task) => task.taskId === taskId) || null;
}

module.exports = {
  WRITING_TASKS,
  tasksForPathway,
  writingTaskById,
};

