'use strict';

const ALL_HEALTHCARE_PROFESSIONS = ['doctor', 'nurse', 'practical_nurse'];

function makeWritingTask(input) {
  const professional = input.pathway === 'professional';
  const checks = [
    {
      id: `${input.taskId}.communicative-goal`,
      area: 'communicative_goal',
      priority: 1,
      condition: { kind: 'includes_each_group', groups: input.requiredGroups },
      successMessage: 'Tehtävän olennaiset asiat näkyvät tekstissäsi.',
      title: 'Varmista, että ydinasia on mukana',
      explanation: input.goalFeedback,
      retryInstruction: input.goalRetry,
    },
    {
      id: `${input.taskId}.minimum-words`,
      area: 'content',
      priority: 2,
      condition: { kind: 'minimum_words', minimum: input.wordTarget.min },
      successMessage: 'Tekstissä on riittävästi sisältöä tehtävän tavoitteen välittämiseen.',
      title: 'Kehitä viestiä yhdellä olennaisella yksityiskohdalla',
      explanation: 'Liian lyhyt teksti voi jättää vastaanottajalle tärkeän tiedon epäselväksi.',
      retryInstruction: 'Lisää yksi tehtävässä annettu olennainen tieto tai perustelu.',
    },
    {
      id: `${input.taskId}.minimum-sentences`,
      area: 'organization',
      priority: 3,
      condition: { kind: 'minimum_sentences', minimum: input.minimumSentences },
      successMessage: 'Teksti on jäsennelty useampaan selkeään virkkeeseen.',
      title: 'Jäsennä teksti lukijalle',
      explanation: 'Selkeä virkejako auttaa lukijaa erottamaan tilanteen, tavoitteen ja seuraavan vaiheen.',
      retryInstruction: 'Jaa keskeiset asiat omiin virkkeisiinsä ja tarkista niiden looginen järjestys.',
    },
  ];

  if (input.register !== 'informal') {
    checks.push({
      id: `${input.taskId}.register`,
      area: 'register',
      priority: 4,
      condition: {
        kind: 'excludes_all',
        terms: ['ihan kamala', 'tosi tyhmä', 'mokasivat', 'joku tyyppi'],
      },
      successMessage: 'Sävy sopii tilanteen vastaanottajalle.',
      title: 'Pidä sävy tilanteeseen sopivana',
      explanation: 'Neutraali tai muodollinen teksti perustuu havaintoihin ja täsmällisiin pyyntöihin.',
      retryInstruction: 'Korvaa arvottava tai epämääräinen ilmaus konkreettisella havainnolla, pyynnöllä tai perustelulla.',
    });
  }

  return {
    taskId: input.taskId,
    contentVersion: '2026-09-27.1',
    pathway: input.pathway,
    level: input.level,
    title: input.title,
    genre: input.genre,
    register: input.register,
    audience: input.audience,
    situation: input.situation,
    communicativeGoal: input.communicativeGoal,
    prompt: input.prompt,
    estimatedMinutes: input.estimatedMinutes,
    wordTarget: input.wordTarget,
    requiredEntitlements: [professional ? 'professionalAccess' : 'learnAccess'],
    ...(professional ? { allowedProfessions: ALL_HEALTHCARE_PROFESSIONS } : {}),
    topic: input.topic,
    scaffolding: {
      showPhraseBank: Boolean(input.phraseStarters?.length),
      planPrompts: input.planPrompts,
      phraseStarters: input.phraseStarters ?? [],
    },
    feedbackChecks: checks,
    successCopy: input.successCopy,
    developingCopy: input.developingCopy,
    ...(professional
      ? {
          privacyNotice:
            'Käytä vain tämän fiktiivisen harjoituksen tietoja. Älä kirjoita oikeita potilas-, asiakas-, henkilöstö- tai muita luottamuksellisia tietoja.',
        }
      : {}),
    originalContent: true,
  };
}

const EVERYDAY_WRITING_EXPANSION = [
  makeWritingTask({
    taskId: 'writing.everyday.neighbour-noise.a1',
    pathway: 'everyday',
    level: 'A1',
    title: 'Kirjoita lyhyt viesti naapurille',
    genre: 'short_message',
    register: 'informal',
    audience: 'Naapuri',
    situation: 'Naapuri jätti sinulle viestin: “Meillä on juhlat lauantaina. Haittaako musiikki?” Haluat pyytää, että musiikki hiljenee kello 22.',
    communicativeGoal: 'Vastaa ystävällisesti ja kerro selkeästi, mihin aikaan toivot hiljaisempaa musiikkia.',
    prompt: 'Kirjoita 2–3 lyhyttä lausetta suomeksi.',
    estimatedMinutes: 6,
    wordTarget: { min: 8, max: 35 },
    topic: 'neighbours',
    planPrompts: [
      { id: 'reply', prompt: 'Miten vastaat?', placeholder: 'Kiitos viestistä…' },
      { id: 'time', prompt: 'Mihin aikaan musiikki hiljenee?', placeholder: 'Kello 22' },
    ],
    phraseStarters: ['Hei!', 'Kiitos viestistä.', 'Voisitteko…?', 'Kello 22 jälkeen…', 'Mukavaa iltaa!'],
    requiredGroups: [['22', 'kymmenen'], ['musiikki', 'hiljaisempi', 'hiljentää']],
    minimumSentences: 2,
    goalFeedback: 'Naapurin pitää ymmärtää sekä toiveesi että kellonaika.',
    goalRetry: 'Lisää kohtelias pyyntö ja mainitse kello 22.',
    successCopy: 'Naapuri ymmärtää toiveesi ja ajan.',
    developingCopy: 'Viestin sävy on ystävällinen, mutta pyyntö tai kellonaika tarvitsee vielä täsmennystä.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.course-cancel.a2',
    pathway: 'everyday',
    level: 'A2',
    title: 'Peru kurssipaikka',
    genre: 'service_message',
    register: 'neutral',
    audience: 'Kansalaisopiston asiakaspalvelu',
    situation: 'Olet ilmoittautunut suomen keskustelukurssille, joka alkaa 6.10. Et pääse osallistumaan ja haluat vapauttaa paikan toiselle.',
    communicativeGoal: 'Kerro, mille kurssille olet ilmoittautunut, peru paikka ja pyydä vahvistus peruutuksesta.',
    prompt: 'Kirjoita lyhyt viesti kansalaisopistolle.',
    estimatedMinutes: 8,
    wordTarget: { min: 20, max: 60 },
    topic: 'courses',
    planPrompts: [
      { id: 'course', prompt: 'Mikä kurssi?', placeholder: 'Suomen keskustelukurssi' },
      { id: 'cancel', prompt: 'Mitä pyydät?', placeholder: 'Perun paikkani' },
      { id: 'confirm', prompt: 'Mitä haluat lopuksi?', placeholder: 'Vahvistus peruutuksesta' },
    ],
    phraseStarters: ['Hei, olen ilmoittautunut…', 'En valitettavasti pääse osallistumaan.', 'Haluaisin perua paikkani.', 'Voisitteko vahvistaa peruutuksen?'],
    requiredGroups: [['keskustelukurssi', 'kurssi'], ['perua', 'perun', 'peruutus'], ['vahvistaa', 'vahvistus']],
    minimumSentences: 3,
    goalFeedback: 'Palvelun pitää tunnistaa kurssi, peruutus ja vahvistuspyyntö.',
    goalRetry: 'Mainitse kurssi, peru paikka selkeästi ja pyydä vahvistus.',
    successCopy: 'Asiakaspalvelu pystyy käsittelemään peruutuksen ilman lisäkysymyksiä.',
    developingCopy: 'Peruutus näkyy, mutta kurssi tai vahvistuspyyntö tarvitsee vielä täsmennystä.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.school-message.b1',
    pathway: 'everyday',
    level: 'B1',
    title: 'Kysy koulun retkestä',
    genre: 'practical_email',
    register: 'neutral',
    audience: 'Opettaja',
    situation: 'Lapsesi luokka lähtee retkelle perjantaina. Tiedät lähtöajan, mutta et paluuaikaa etkä sitä, tarvitseeko lapsi oman evään.',
    communicativeGoal: 'Kerro, mihin retkeen kysymyksesi liittyy ja pyydä kaksi puuttuvaa käytännön tietoa.',
    prompt: 'Kirjoita selkeä viesti opettajalle.',
    estimatedMinutes: 10,
    wordTarget: { min: 40, max: 100 },
    topic: 'school',
    planPrompts: [
      { id: 'context', prompt: 'Mistä retkestä on kyse?', placeholder: 'Perjantain retki' },
      { id: 'return', prompt: 'Mitä kysyt paluuajasta?', placeholder: 'Milloin luokka palaa?' },
      { id: 'food', prompt: 'Mitä kysyt eväistä?', placeholder: 'Tarvitaanko oma eväs?' },
    ],
    phraseStarters: [],
    requiredGroups: [['perjantai', 'retki'], ['palaa', 'paluu', 'paluuaika'], ['eväs', 'eväät']],
    minimumSentences: 4,
    goalFeedback: 'Opettajan pitää nähdä sekä retken yhteys että kaksi erillistä kysymystä.',
    goalRetry: 'Kysy paluuaika ja se, tarvitseeko lapsi oman evään.',
    successCopy: 'Opettaja voi vastata molempiin käytännön kysymyksiin.',
    developingCopy: 'Retki tunnistuu, mutta yksi tarvittava kysymys puuttuu.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.refund-request.b2',
    pathway: 'everyday',
    level: 'B2',
    title: 'Perustele hyvityspyyntö',
    genre: 'formal_request',
    register: 'formal',
    audience: 'Palveluntarjoajan asiakaspalvelu',
    situation: 'Maksoit verkkokurssista, mutta palvelu oli teknisen häiriön vuoksi kokonaan poissa käytöstä kolme ensimmäistä päivää. Palveluntarjoaja tarjosi yhden lisäpäivän, mutta pyydät laajempaa hyvitystä.',
    communicativeGoal: 'Kuvaa häiriö, arvioi tarjotun ratkaisun riittävyys ja perustele kohtuullinen hyvityspyyntö.',
    prompt: 'Kirjoita asiallinen hyvityspyyntö.',
    estimatedMinutes: 14,
    wordTarget: { min: 80, max: 170 },
    topic: 'consumer_service',
    planPrompts: [
      { id: 'problem', prompt: 'Mitä tapahtui?', placeholder: 'Palvelu ei toiminut kolmeen päivään' },
      { id: 'offer', prompt: 'Mitä sinulle tarjottiin?', placeholder: 'Yksi lisäpäivä' },
      { id: 'request', prompt: 'Mitä pyydät ja miksi?', placeholder: 'Kohtuullinen hyvitys + perustelu' },
    ],
    requiredGroups: [['kolme', '3'], ['lisäpäivä', 'yksi päivä'], ['hyvitys', 'korvaus'], ['koska', 'sen vuoksi', 'perustelen']],
    minimumSentences: 5,
    goalFeedback: 'B2-tasolla pyynnön pitää yhdistää tapahtuma, tarjottu ratkaisu ja perusteltu vastapyyntö.',
    goalRetry: 'Yhdistä kolmen päivän käyttökatko, yhden päivän tarjous ja perusteltu hyvityspyyntö.',
    successCopy: 'Vastaanottaja ymmärtää sekä vaatimuksen että sen perustelut.',
    developingCopy: 'Pyyntö näkyy, mutta perustelu tai vertailu tarjottuun ratkaisuun jää vajaaksi.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.housing-proposal.b2',
    pathway: 'everyday',
    level: 'B2',
    title: 'Tee ehdotus taloyhtiölle',
    genre: 'proposal_message',
    register: 'neutral',
    audience: 'Taloyhtiön hallitus',
    situation: 'Pyörävarasto on usein täynnä käytöstä poistuneita pyöriä. Haluat ehdottaa vuosittaista merkintäkierrosta, jossa omistamattomiksi jääneet pyörät käsitellään yhtiön sääntöjen mukaisesti.',
    communicativeGoal: 'Kuvaa ongelma, ehdota menettelyä ja perustele, miten se parantaisi tilan käyttöä ilman perusteettomia oletuksia omistuksesta.',
    prompt: 'Kirjoita hallitukselle perusteltu ehdotus.',
    estimatedMinutes: 14,
    wordTarget: { min: 80, max: 170 },
    topic: 'housing',
    planPrompts: [
      { id: 'problem', prompt: 'Mikä käytännön ongelma on?', placeholder: 'Varasto on täynnä' },
      { id: 'proposal', prompt: 'Mitä ehdotat?', placeholder: 'Vuosittainen merkintäkierros' },
      { id: 'boundary', prompt: 'Miten vältät väärät oletukset?', placeholder: 'Yhtiön sääntöjen mukainen käsittely' },
    ],
    requiredGroups: [['pyörävarasto', 'varasto'], ['merkintä', 'vuosittainen'], ['sääntö', 'menettely'], ['tila', 'käyttö']],
    minimumSentences: 5,
    goalFeedback: 'Ehdotuksessa pitää näkyä sekä käytännön hyöty että asianmukainen menettely.',
    goalRetry: 'Kuvaa ongelma, vuosittainen merkintäkierros ja sääntöihin perustuva jatkokäsittely.',
    successCopy: 'Hallitus saa toteuttamiskelpoisen ja rajatun ehdotuksen.',
    developingCopy: 'Idea näkyy, mutta menettely tai perustelu tarvitsee täsmennystä.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.public-comment.c1',
    pathway: 'everyday',
    level: 'C1',
    title: 'Kirjoita rakentava lausuntopalaute',
    genre: 'public_comment',
    register: 'formal',
    audience: 'Kaupungin suunnitteluyksikkö',
    situation: 'Kaupunki ehdottaa kirjaston aukiolon lyhentämistä kahtena arki-iltana ja vastaavasti sunnuntaiajan pidentämistä. Käytät kirjastoa työpäivien jälkeen ja ymmärrät samalla sunnuntaiaukiolon hyödyn.',
    communicativeGoal: 'Ota perusteltu kanta, tunnista ehdotuksen hyöty ja esitä vaihtoehto, joka huomioi eri käyttäjäryhmiä.',
    prompt: 'Kirjoita tiivis mutta argumentoitu lausuntopalaute.',
    estimatedMinutes: 18,
    wordTarget: { min: 120, max: 230 },
    topic: 'public_services',
    planPrompts: [
      { id: 'position', prompt: 'Mikä on kantasi?', placeholder: 'Arki-iltoja ei pitäisi lyhentää näin paljon' },
      { id: 'concession', prompt: 'Minkä hyödyn tunnistat?', placeholder: 'Sunnuntaiaukiolo auttaa osaa käyttäjistä' },
      { id: 'alternative', prompt: 'Mitä vaihtoehtoa ehdotat?', placeholder: 'Pienempi muutos / kokeilu / seuranta' },
    ],
    requiredGroups: [['arki', 'ilta'], ['sunnuntai'], ['ehdotan', 'vaihtoehto', 'kokeilu'], ['toisaalta', 'samalla', 'vaikka']],
    minimumSentences: 7,
    goalFeedback: 'C1-tasolla kannan pitää tunnistaa vastakkaisen ratkaisun hyöty ja rakentaa perusteltu vaihtoehto.',
    goalRetry: 'Tee kantasi näkyväksi, myönnä sunnuntaiaukiolon hyöty ja ehdota perusteltu kompromissi.',
    successCopy: 'Palaute on argumentoitu, tasapainoinen ja päätöksenteon kannalta käyttökelpoinen.',
    developingCopy: 'Kanta näkyy, mutta vastanäkökulma tai vaihtoehdon perustelu jää ohueksi.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.contract-clarification.c1',
    pathway: 'everyday',
    level: 'C1',
    title: 'Pyydä sopimusehdon täsmennystä',
    genre: 'formal_email',
    register: 'formal',
    audience: 'Palveluntarjoajan sopimusasiantuntija',
    situation: 'Sopimuksessa sanotaan, että “olennaiset muutokset” voivat oikeuttaa hinnan tarkistamiseen, mutta ilmausta ei määritellä. Ennen hyväksymistä haluat tietää, mitä muutoksia sillä tarkoitetaan ja miten niistä ilmoitetaan.',
    communicativeGoal: 'Rajaa epäselvä kohta, esitä täsmälliset kysymykset ja kerro, miksi tiedot vaikuttavat päätökseesi.',
    prompt: 'Kirjoita selkeä täsmennyspyyntö.',
    estimatedMinutes: 18,
    wordTarget: { min: 110, max: 220 },
    topic: 'contracts',
    planPrompts: [
      { id: 'clause', prompt: 'Mikä ilmaus on epäselvä?', placeholder: '“Olennaiset muutokset”' },
      { id: 'questions', prompt: 'Mitä haluat tietää?', placeholder: 'Määritelmä + ilmoitusmenettely' },
      { id: 'reason', prompt: 'Miksi tieto on tarpeen?', placeholder: 'Vaikuttaa sopimuksen hyväksymiseen' },
    ],
    requiredGroups: [['olennainen', 'muutos'], ['tarkoittaa', 'määritelmä'], ['ilmoittaa', 'ilmoitus'], ['päätös', 'hyväksyä', 'sopimus']],
    minimumSentences: 6,
    goalFeedback: 'Täsmennyspyynnön pitää yksilöidä epäselvä ehto ja pyytää päätöksenteon kannalta olennaiset tiedot.',
    goalRetry: 'Nimeä ehto, kysy sen merkitys ja ilmoitusmenettely sekä kerro, miksi tarvitset tiedon.',
    successCopy: 'Vastaanottaja pystyy vastaamaan täsmällisesti siihen, mitä sopimuksesta puuttuu.',
    developingCopy: 'Epäselvä kohta tunnistuu, mutta kysymykset tai niiden merkitys päätöksellesi jäävät yleisiksi.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.synthesis.c2',
    pathway: 'everyday',
    level: 'C2',
    title: 'Tiivistä ristiriitaiset näkökulmat',
    genre: 'analytical_summary',
    register: 'formal',
    audience: 'Kansalaisryhmän keskustelutilaisuus',
    situation: 'Kaksi ryhmää arvioi keskustan liikennemuutosta eri tavoin: toinen painottaa saavutettavuutta autolla, toinen kävelyn ja joukkoliikenteen sujuvuutta. Molemmat viittaavat puutteelliseen seurantatietoon.',
    communicativeGoal: 'Laadi neutraali synteesi, joka erottaa yhteisen tiedollisen epävarmuuden ryhmien erilaisista arvopainotuksista.',
    prompt: 'Kirjoita tiivis synteesi ilman että valitset voittavaa osapuolta.',
    estimatedMinutes: 20,
    wordTarget: { min: 140, max: 260 },
    topic: 'synthesis',
    planPrompts: [
      { id: 'shared', prompt: 'Mistä ryhmät ovat epäsuorasti samaa mieltä?', placeholder: 'Seurantatieto on puutteellista' },
      { id: 'difference', prompt: 'Missä painotukset eroavat?', placeholder: 'Autojen saavutettavuus vs kävely/joukkoliikenne' },
      { id: 'synthesis', prompt: 'Miten erotat tiedon ja arvovalinnan?', placeholder: 'Epävarmuus + eri tavoitteet' },
    ],
    requiredGroups: [['saavutettavuus', 'auto'], ['kävely', 'joukkoliikenne'], ['seuranta', 'tieto', 'epävarmuus'], ['toisaalta', 'kun taas', 'molemmat']],
    minimumSentences: 8,
    goalFeedback: 'C2-synteesissä yhteinen epävarmuus ja eri arvopainotukset pitää erottaa ilman yksinkertaistavaa paremmuusjärjestystä.',
    goalRetry: 'Nimeä molempien ryhmien painotus, yhteinen tiedonpuute ja niiden välinen ero.',
    successCopy: 'Synteesi säilyttää osapuolten erot ja yhteisen epävarmuuden ilman väärää tasapäistämistä.',
    developingCopy: 'Molemmat näkökulmat näkyvät, mutta tiedollinen epävarmuus ja arvopainotus sekoittuvat vielä.',
  }),
  makeWritingTask({
    taskId: 'writing.everyday.formal-response.c2',
    pathway: 'everyday',
    level: 'C2',
    title: 'Muotoile täsmällinen vastine',
    genre: 'formal_response',
    register: 'formal',
    audience: 'Taloyhtiön hallitus ja osakkaat',
    situation: 'Kokousmuistiossa väitetään, että vastustit koko piharemonttia. Todellisuudessa vastustit vain aikataulua, koska esteettömän kulun väliaikaisjärjestelyä ei ollut kuvattu. Kannatat itse remontin tavoitetta.',
    communicativeGoal: 'Oikaise väite ilman tarpeetonta kärjistystä, rajaa erimielisyys tarkasti ja säilytä yhteistyöhakuinen sävy.',
    prompt: 'Kirjoita muodollinen mutta rakentava vastine.',
    estimatedMinutes: 20,
    wordTarget: { min: 130, max: 250 },
    topic: 'formal_response',
    planPrompts: [
      { id: 'incorrect', prompt: 'Mikä väite on virheellinen?', placeholder: 'En vastustanut koko remonttia' },
      { id: 'actual', prompt: 'Mitä oikeasti vastustit?', placeholder: 'Aikataulua ilman esteettömän kulun suunnitelmaa' },
      { id: 'common', prompt: 'Mitä tavoitetta tuet?', placeholder: 'Remontin tavoitetta' },
    ],
    requiredGroups: [['en vastusta', 'kannatan', 'tavoite'], ['aikataulu'], ['esteetön', 'kulku'], ['oikaista', 'täsmennän', 'muistio']],
    minimumSentences: 7,
    goalFeedback: 'Vastineen pitää oikaista väite ja rajata todellinen erimielisyys ilman että yhteistyöhalu katoaa.',
    goalRetry: 'Kerro, mitä et vastustanut, mitä vastustit ja mikä yhteinen tavoite säilyy.',
    successCopy: 'Vastine oikaisee asian täsmällisesti ja pitää erimielisyyden rajattuna.',
    developingCopy: 'Oikaisu näkyy, mutta todellinen erimielisyys tai yhteinen tavoite tarvitsee vielä tarkemman rajauksen.',
  }),
];

const PROFESSIONAL_WRITING_EXPANSION = [
  makeWritingTask({
    taskId: 'writing.professional.meeting-actions.b1',
    pathway: 'professional',
    level: 'B1',
    title: 'Kirjaa kokouksen jatkotoimet',
    genre: 'internal_update',
    register: 'professional_neutral',
    audience: 'Tiimi',
    situation: 'Fiktiivisessä kokouksessa sovittiin, että Anna kokoaa palautteet torstaihin mennessä, Mika tarkistaa luvut ja koko tiimi lukee perehdytysohjeen ennen maanantaita.',
    communicativeGoal: 'Kirjoita tiivis yhteenveto, jossa tehtävä, vastuuhenkilö ja määräaika eivät sekoitu.',
    prompt: 'Kirjoita tiimille selkeä jatkotoimiviesti.',
    estimatedMinutes: 11,
    wordTarget: { min: 45, max: 110 },
    topic: 'meeting_actions',
    planPrompts: [
      { id: 'anna', prompt: 'Mitä Anna tekee ja milloin?', placeholder: 'Palautteet torstaihin' },
      { id: 'mika', prompt: 'Mitä Mika tekee?', placeholder: 'Tarkistaa luvut' },
      { id: 'team', prompt: 'Mitä koko tiimi tekee?', placeholder: 'Lukee ohjeen ennen maanantaita' },
    ],
    requiredGroups: [['Anna', 'palautteet'], ['Mika', 'luvut'], ['maanantai', 'perehdytysohje']],
    minimumSentences: 4,
    goalFeedback: 'Työviestin pitää yhdistää oikea vastuu oikeaan tehtävään ja määräaikaan.',
    goalRetry: 'Kirjoita erikseen Annan, Mikan ja koko tiimin jatkotoimet.',
    successCopy: 'Tiimi näkee yhdellä lukemisella, kuka tekee mitä ja milloin.',
    developingCopy: 'Tehtäviä on mukana, mutta vastuut tai määräajat eivät vielä erotu riittävän selvästi.',
  }),
  makeWritingTask({
    taskId: 'writing.professional.process-change.b2',
    pathway: 'professional',
    level: 'B2',
    title: 'Perustele prosessimuutos tiimille',
    genre: 'change_update',
    register: 'professional_neutral',
    audience: 'Työtiimi',
    situation: 'Fiktiivinen tiimi siirtyy kahdesta erillisestä käsittelyjonosta yhteen yhteiseen jonoon. Tavoitteena on nähdä kuormitus paremmin, mutta ensimmäisten viikkojen aikana luokittelu voi hidastaa työtä.',
    communicativeGoal: 'Selitä muutos, sen tavoite, siirtymävaiheen haitta ja se, miten onnistumista seurataan.',
    prompt: 'Kirjoita tiimille muutosviesti.',
    estimatedMinutes: 15,
    wordTarget: { min: 85, max: 180 },
    topic: 'process_change',
    planPrompts: [
      { id: 'change', prompt: 'Mikä muuttuu?', placeholder: 'Kaksi jonoa → yksi yhteinen jono' },
      { id: 'benefit', prompt: 'Miksi muutos tehdään?', placeholder: 'Kuormitus näkyy paremmin' },
      { id: 'transition', prompt: 'Mikä voi aluksi vaikeutua?', placeholder: 'Luokittelu hidastaa' },
    ],
    requiredGroups: [['yhteinen', 'jono'], ['kuormitus', 'näkyvyys'], ['aluksi', 'siirtymä', 'hidastua'], ['seurata', 'arvioida', 'onnistuminen']],
    minimumSentences: 6,
    goalFeedback: 'B2-muutosviestin pitää yhdistää tavoite, kustannus/haitta ja seuranta.',
    goalRetry: 'Kuvaa uusi jono, tavoite, alun hidastuminen ja se, miten vaikutusta seurataan.',
    successCopy: 'Tiimi ymmärtää sekä muutoksen syyn että siirtymävaiheen realistiset odotukset.',
    developingCopy: 'Muutos näkyy, mutta tavoite, haitta tai seuranta tarvitsee vielä perustelua.',
  }),
  makeWritingTask({
    taskId: 'writing.professional.stakeholder-recommendation.c1',
    pathway: 'professional',
    level: 'C1',
    title: 'Laadi sidosryhmäsuositus',
    genre: 'recommendation_memo',
    register: 'formal',
    audience: 'Projektin ohjausryhmä',
    situation: 'Fiktiivisessä projektissa voidaan käynnistää pilotti marraskuussa vain, jos sisältörunko vahvistetaan 20.10. mennessä. Myöhäiset muutokset ovat mahdollisia, mutta ne voivat siirtää aikataulua.',
    communicativeGoal: 'Suosittele etenemistapaa, tee riippuvuus näkyväksi ja rajaa, mitä voidaan luvata ilman lisävahvistusta.',
    prompt: 'Kirjoita lyhyt suositus ohjausryhmälle.',
    estimatedMinutes: 18,
    wordTarget: { min: 120, max: 230 },
    topic: 'stakeholder_management',
    planPrompts: [
      { id: 'recommendation', prompt: 'Mitä suosittelet?', placeholder: 'Vahvistetaan runko määräpäivään mennessä' },
      { id: 'dependency', prompt: 'Mistä aikataulu riippuu?', placeholder: '20.10. vahvistuksesta' },
      { id: 'boundary', prompt: 'Mitä ei voi luvata etukäteen?', placeholder: 'Myöhäisten muutosten vaikutusta' },
    ],
    requiredGroups: [['20.10', '20.10.'], ['marraskuu', 'pilotti'], ['muutos', 'aikataulu'], ['suosittelen', 'suositus']],
    minimumSentences: 7,
    goalFeedback: 'Suosituksen pitää tehdä sekä etenemisehto että myöhempien muutosten epävarmuus näkyväksi.',
    goalRetry: 'Suosittele etenemistä, nimeä 20.10. riippuvuus ja rajaa myöhäisten muutosten vaikutus.',
    successCopy: 'Ohjausryhmä saa päätöksentekoa tukevan suosituksen ilman ylilupausta.',
    developingCopy: 'Suositus näkyy, mutta ehto tai muutosten vaikutus jää liian implisiittiseksi.',
  }),
  makeWritingTask({
    taskId: 'writing.professional.risk-note.c1',
    pathway: 'professional',
    level: 'C1',
    title: 'Kirjoita päätösvalmistelun riskihuomio',
    genre: 'decision_note',
    register: 'formal',
    audience: 'Esihenkilö ja päätösvalmistelijat',
    situation: 'Fiktiivisen uudistuksen ensimmäinen mittari näyttää käsittelyajan lyhentyneen, mutta samalla uudelleenohjausten määrä kasvoi. Et halua päätellä onnistumista yhden mittarin perusteella.',
    communicativeGoal: 'Erota havainto tulkinnasta, nimeä ristiriitainen signaali ja ehdota, mitä lisätietoa ennen päätöstä tarvitaan.',
    prompt: 'Kirjoita neutraali riskihuomio päätösvalmisteluun.',
    estimatedMinutes: 18,
    wordTarget: { min: 120, max: 230 },
    topic: 'decision_support',
    planPrompts: [
      { id: 'positive', prompt: 'Mikä näyttää parantuneen?', placeholder: 'Käsittelyaika' },
      { id: 'counter', prompt: 'Mikä ristiriitainen havainto on?', placeholder: 'Uudelleenohjaukset lisääntyivät' },
      { id: 'need', prompt: 'Mitä tietoa tarvitaan?', placeholder: 'Kokonaiskontaktit / syyt / pidempi seuranta' },
    ],
    requiredGroups: [['käsittelyaika'], ['uudelleenohjaus', 'ohjattu uudelleen'], ['ei yksin', 'yksi mittari', 'samalla'], ['lisätieto', 'seuranta', 'tarvitaan']],
    minimumSentences: 7,
    goalFeedback: 'C1-riskihuomiossa myönteinen havainto ja sitä rajoittava signaali pitää erottaa tulkinnasta.',
    goalRetry: 'Nimeä lyhentynyt käsittelyaika, kasvaneet uudelleenohjaukset ja tarvittava lisäseuranta.',
    successCopy: 'Huomio tukee harkintaa eikä tee vahvempaa johtopäätöstä kuin aineisto sallii.',
    developingCopy: 'Riski tunnistuu, mutta havainto, tulkinta ja tarvittava lisätieto sekoittuvat vielä.',
  }),
  makeWritingTask({
    taskId: 'writing.professional.executive-summary.c2',
    pathway: 'professional',
    level: 'C2',
    title: 'Tiivistä päätöksenteon epävarmuus',
    genre: 'executive_summary',
    register: 'formal',
    audience: 'Johtoryhmä',
    situation: 'Fiktiivisessä analyysissä digitaalinen kanava on halvempi ensikontaktissa, mutta aineistosta puuttuu tieto siitä, lisääkö epäonnistunut itsepalvelu myöhempiä yhteydenottoja. Vakioitavissa palveluissa hyöty näyttää selvältä, harkintaa vaativissa ei.',
    communicativeGoal: 'Laadi tiivis yhteenveto, joka erottaa vahvan havainnon, olennaisen tiedonpuutteen ja ehdollisen suosituksen.',
    prompt: 'Kirjoita johtoryhmälle enintään noin yhden sivun tiivistelmä.',
    estimatedMinutes: 22,
    wordTarget: { min: 150, max: 280 },
    topic: 'executive_summary',
    planPrompts: [
      { id: 'known', prompt: 'Mitä aineisto tukee?', placeholder: 'Ensikontakti on halvempi / vakioitavat palvelut' },
      { id: 'unknown', prompt: 'Mitä emme tiedä?', placeholder: 'Uusintakontaktien vaikutus' },
      { id: 'recommendation', prompt: 'Mikä ehdollinen suositus seuraa?', placeholder: 'Vaiheittainen eteneminen + seuranta' },
    ],
    requiredGroups: [['ensikontakti', 'halvempi'], ['uusinta', 'myöhempi', 'kokonaiskontaktit'], ['vakio', 'harkinta'], ['vaiheittain', 'seuranta', 'jos']],
    minimumSentences: 8,
    goalFeedback: 'C2-yhteenvedon pitää säilyttää evidenssin rajat ja tehdä suosituksen ehdollisuus eksplisiittiseksi.',
    goalRetry: 'Erota havaittu kustannushyöty, puuttuva uusintakontaktitieto ja vaiheittainen suositus.',
    successCopy: 'Johtoryhmä saa tiiviin kuvan siitä, mitä tiedetään, mitä ei tiedetä ja mitä voidaan silti suositella.',
    developingCopy: 'Pääkohdat näkyvät, mutta tiedonpuute tai suosituksen ehdollisuus latistuu liian varmaksi.',
  }),
  makeWritingTask({
    taskId: 'writing.professional.policy-clarification.c2',
    pathway: 'professional',
    level: 'C2',
    title: 'Täsmennä ohjeen soveltamisraja',
    genre: 'policy_clarification',
    register: 'formal',
    audience: 'Henkilöstö ja esihenkilöt',
    situation: 'Fiktiivisessä ohjeessa määräaikaa voidaan ylittää vain, jos luotettava ratkaisu vaatii tietoa, jota ei kohtuudella saada ajoissa. Poikkeusta ei saa käyttää ennakoitavan resurssivajeen yleisenä keinona.',
    communicativeGoal: 'Selitä pääsääntö, rajattu poikkeus ja tapaus, johon poikkeusta ei pidä laajentaa.',
    prompt: 'Kirjoita henkilöstölle täsmentävä ohjeteksti ilman uuden säännön keksimistä.',
    estimatedMinutes: 22,
    wordTarget: { min: 140, max: 270 },
    topic: 'policy_clarification',
    planPrompts: [
      { id: 'rule', prompt: 'Mikä on pääsääntö?', placeholder: 'Määräaikaa noudatetaan' },
      { id: 'exception', prompt: 'Milloin poikkeus on mahdollinen?', placeholder: 'Olennainen tieto ei ole kohtuudella saatavissa' },
      { id: 'not', prompt: 'Mihin poikkeusta ei käytetä?', placeholder: 'Ennakoitavan resurssivajeen tasaamiseen' },
    ],
    requiredGroups: [['määräaika', 'pääsääntö'], ['luotettava', 'tieto', 'kohtuudella'], ['poikkeus'], ['resurssi', 'vaje', 'ei käytetä']],
    minimumSentences: 8,
    goalFeedback: 'C2-ohjetekstin pitää säilyttää alkuperäisen säännön rajat: poikkeusta ei saa muuttaa yleiseksi joustoksi.',
    goalRetry: 'Kirjoita pääsääntö, poikkeuksen täsmällinen ehto ja resurssivajetta koskeva rajoitus.',
    successCopy: 'Ohjeen soveltamisraja on täsmällinen eikä laajenna poikkeusta alkuperäistä pidemmälle.',
    developingCopy: 'Sääntö ja poikkeus näkyvät, mutta niiden välinen raja tai poissuljettu tapaus tarvitsee täsmennystä.',
  }),
];

module.exports = {
  EVERYDAY_WRITING_EXPANSION,
  PROFESSIONAL_WRITING_EXPANSION,
};
